version: "3.3"
services:
  web:
    image: "otcurrencyweb"
    build: .
    ports:
      - "8080:80"
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      MONGODB_HOST: "mongo"
      MONGODB_PORT: 27017
      MONGODB_DB: "otcurrency"
      GOOGLEAUTH_CLIENT_ID: "Client ID"
      GOOGLEAUTH_CLIENT_SECRET: "Client Secret"
      URLHOST: "localhost:8080"
    networks:
      - webnet
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: otcurrency
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - webnet
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - webnet
networks:
  webnet: